#!/bin/bash
# Description
#   Brings together all the tools for managing mass
#
# Syntax:
#   $0 scriptName [parameters]
#      scriptName is one of the possible scripts listed below. Use --help with the script to find out more about it.
#
# Examples:
#   Lists the current repos including any ssymlink infomation.
#     $0 repo-list
#   Adds /usr/blah 
#     $0 repo-pretend /usr/blah
#   Display the help for repo-add
#     $0 repo-add --help
#   
#

export configDir=`mass --get=General,configDir --singleStringNow --null`
export libDir=$configDir/supplimentary/libs
export supplimentaryDir=$configDir/supplimentary

. $libDir/theLibOfLibs.sh

# Possible scripts:
extraHelp='displayListOfSupplimeentaryScripts'
requiredParms="$1"
. $libDir/help.sh

name=`echo $0 | sed 's#.*/##g'`

script=""$supplimentaryDir/$1""
if [ -f "$script" ]; then
	export scriptName="$name $1"
	shift
	"$script" $@
else
	case $1 in
		'--help'|'-h')
			showHelp
		;;
		*)
			echo "Could not find \"$1\""
			showHelp
		;;
	esac
fi
