#!/bin/bash
# Description
#   Brings together all the tools for managing mass
#
# Syntax:
#   $0 scriptName [parameters]
#
# Examples:
#   Lists the current repos including any ssymlink infomation.
#     $0 repo-list
#   Adds /usr/blah 
#     $0 repo-pretend /usr/blah

configDir=`mass --get=General,configDir --singleStringNow --null`
libDir=$configDir/supplimentary/libs
supplimentaryDir=$configDir/supplimentary

. $libDir/theLibOfLibs.sh
extraHelp='displayListOfSupplimeentaryScripts'
. $libDir/help.sh

name=`echo $0 | sed 's#.*/##g'`
# TODO tidy/finish this
# function showHelp
# {
# 	echo "Syntax:"
# 	echo "  $name scriptName [options]"
# 	echo
# 	echo "Possible scripts:"
# 	displayListOfSupplimeentaryScripts
# 	exit 1
# }
# 
# if [ "$1" == "" ]; then
# 	echo "Insufficient parameters given."
# 	showHelp
# fi

script=""$supplimentaryDir/$1""
if [ -f "$script" ]; then
	export scriptName="$name $1"
	shift
	"$script" $@
else
	case $1 in
		'--help'|'-h')
			showHelp
		;;
		*)
			echo "Could not find \"$1\""
			showHelp
		;;
	esac
fi
