#!/usr/bin/php
<?php
# Copyright (c) 2012, Kevin Sandom under the BSD License. See LICENSE for full details.
 
define('programName', 'mass');
$description="A script for doing awesome stuff on many nodes of a cluster.";

# Find home
$home=trim(`echo \$HOME`); # TODO There is a better way than this!

# Find bzse
if (file_exists("$home/.".programName."/core.php"))
{
	$configDir="$home/.".programName;
}
elseif (file_exists("/etc/".programName."/core.php"))
{
	$configDir="/etc/".programName;
}
else
{
	die (programName.": Could not find installation. Please run install.sh.\n");
}

include "$configDir/core.php";


# initiate core
$core=core::assert();
$core->set('General', 'configDir', $configDir);
$core->set('General', 'programName', programName);
$core->set('General', 'description', $description);
$core->setRef('CommandLine', 'arguments', $argv);
loadModules($core, "$configDir/modules-enabled");

$core->run('Hosts', 'load', "$configDir/data/hosts");
$core->run('CommandLine', 'processArgs');

$core->go();

#$core->dumpState();

?>
