#!/bin/bash
# Description
#   Install the PHP AWS SDK
#
# Syntax:
#   $0
#
# Examples:
#   Simply install it. Boo-ya!
#   $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

. $libDir/getRepo.sh

# Make this work in /repos instead of /externalLibraries
getRepo "aws-sdk-for-php" "git://github.com/rawswift/aws-sdk-for-php.git"
