#!/bin/bash
# Description
#   Install the oauth2-php library
#
# Syntax:
#   $0
#
# Examples:
#   Simply install it. Boo-ya!
#   $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

. $libDir/getRepo.sh

# Make this work in /repos instead of /externalLibraries
getRepo "oauth2-php" "git@github.com:quizlet/oauth2-php.git"
