#!/bin/bash
# Description
#   Install the PHP-OAuth2 library
#
# Syntax:
#   $0
#
# Examples:
#   Simply install it. Boo-ya!
#   $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

. $libDir/getRepo.sh

# Make this work in /repos instead of /externalLibraries
getRepo "PHP-OAuth2" "git@github.com:adoy/PHP-OAuth2.git"
