#!/bin/bash
# Description
#   Installs the google services API tools.
#
# Syntax:
#   $0
#
# Examples:
#   Simply install it. Boo-ya!
#     $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

function installServicesGoogle
{
	pear update-channels
	
	if !pear install Services_Google; then
		echo "Falling back to one that is known to work right now. This will certainly become obsolete sooner or later."
		pear install channel://pear.php.net/Services_Google-0.2.0
	fi
}

if which pear > /dev/null; then
	sudo installServicesGoogle
else
	echo "Pear is not installed. Please install it."
	exit 1
fi
