#!/bin/bash
# Description
#   Installs clusterSSH or the appropriate variant
#
# Syntax:
#   $0
#
# Examples:
#   Simply install it. Boo-ya!
#     $0

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

if which apt-get; then
	echo "Choosing apt based install"
	sudo apt-get install clusterssh
elif which brew; then
	echo "Choosing brew based install"
	brew install csshX
	csshPath=`which csshX`
	cd `dirname $csshPath`
	ln -s csshX cssh
fi
