#!/bin/bash
# Description
#   Enable packages matching a regular expression in profiles matching a regular expression.
#
# Syntax:
#   $0 repoName packageRegex profileNameRegex
#     repoName is the named repository. (found with repoList)
#     packageRegex is a regular expression to match packages found with packageList.
#     profileNameRegex is a regular expression to match profiles found with profileList.
#
# Examples:
#   Enables a package called something in the commandLine profile.
#     $0 mass "^something$" "^commandLine$"
#
#   Enables all packages in the commandLine profile.
#     $0 mass ".*" "^commandLine$"
#
#   Enables all packages in all profiles.
#     $0 mass ".*" ".*"


requiredParms="$3"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/packages.sh

enabledPacakge "$1" "$2" "$3"
