#!/bin/bash
# Description
#   Lists out available packages.
#
# Syntax:
#   $0 [profile] [--short]
#
# Examples:
#   Lists the enabled packages.
#     $0
#   Lists the available packages and guarantees that there is no symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

function listPackagesForProfile
{
	profile="$1"
	resolveSymlinks "$profileDir/$profile/packages"
}

while read profile; do
	listPackagesForProfile "$profile"
done < <($managementTool profileList --short)

