#!/bin/bash
# Description
#   Disable packages matching a regular expression in profiles matching a regular expression.
#
# Syntax:
#   $0 repoName packageRegex profileNameRegex
#     repoName is the named repository. (found with repoList)
#     packageRegex is a regular expression to match packages found with packageList.
#     profileNameRegex is a regular expression to match profiles found with profileList.
#
# Examples:
#   Disables a package called something from the mass repo in the commandLine profile.
#     $0 mass "^something$" "^commandLine$"
#
#   Disables all packages from the mass repo in the commandLine profile.
#     $0 mass ".*" "^commandLine$"
#
#   Disables all packages from the mass repo in all profiles.
#     $0 mass ".*" ".*"


requiredParms="$3"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/packages.sh

disablePackage "$1" "$2" "$3"
