#!/bin/bash
# Description
#   Lists out available packages.
#
# Syntax:
#   $0 [profile] [--short]
#
# Examples:
#   Lists the enabled packages.
#     $0
#   Lists the available packages and guarantees that there is no symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

function listPackagesForProfile
{
	profile="$1"
	while read entry fullPath;do
		realEntryName=`getFile "$fullPath"`
		repoName=`echo "$fullPath" | sed 's#'"$repoDir"'/##g;s#/.*##g'`
		if [ "$short" == 'true' ]; then
			echo "$realEntryName"
		else
			echo "$profile	$repoName	$realEntryName"
		fi
	done < <(resolveSymlinks "$profileDir/$profile/packages")
}

if ! isValue "$1"; then
	while read profile; do
		listPackagesForProfile "$profile" | tabsToSpacedDashes
	done < <($managementTool profileList --short)
else
	listPackagesForProfile "$1" | tabsToSpacedDashes
fi

