#!/bin/bash
# Description
#   Disable packages matching a regular expression in profiles matching a regular expression.
#
# Syntax:
#   $0 repoName packageRegex profileNameRegex
#     repoName is the named repository. (found with repoList)
#     packageRegex is a regular expression to match packages found with packageList.
#     profileNameRegex is a regular expression to match profiles found with profileList.
#
# Examples:
#   Disables a package called something from the mass repo in the commandLine profile.
#     $0 mass "^something$" "^commandLine$"
#
#   Disables all packages from the mass repo in the commandLine profile.
#     $0 mass ".*" "^commandLine$"
#
#   Disables all packages from the mass repo in all profiles.
#     $0 mass ".*" ".*"


requiredParms="$3"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/packages.sh

repoName="$1"
packageRegex="$2"
profileNameRegex="$3"

profiles=`$managementTool profileList | grep "$profileNameRegex"`
if [ "$profiles" == '' ]; then
	echo "Did not match any profiles using regex \"$profileNameRegex\""
	exit 1
fi

while read profile; do
	while read package;do
		packagePath="$configDir/profiles/$profile/packages/$repoName-$package"
		if [ -h "$packagePath" ]; then
			rm -f "$packagePath"
		elif [ -d "$packagePath" ]; then
			echo "$packagePath is a directory. Is this your only copy of your work?! This should be a symlink."
		fi
	done < <($managementTool repoListPackages $repoName --short | grep "$packageRegex")
done < <(echo "$profiles")
