#!/bin/bash
# Description
#   Lists out packages.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the profiles including any symlink infomation.
#   $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#   $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

while read repo; do
	while read package;do 
		echo $repo	$package
	done < <($managementTool repoListPackages $repo)
	
done < <($managementTool repoList --short)

