#!/bin/bash
# Description
#   Lists out profiles.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the profiles including any symlink infomation.
#     $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

case $1 in
	'--short')
		ls -1 "$configDir"/profiles
	;;
	*)
		resolveSymlinks "$configDir"/profiles | tabsToSpacedDashes
	;;
esac
