#!/bin/bash
# Description
#   Adds a new profile, including the full directory structure.
#
# Syntax:
#   $0 profileName
#     profileName is the name for which the profile will programatically be referenced.
#
# Examples:
#   Adds a profile called "lite"
#     $0 lite

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/packages.sh
. "$libDir"/installLibs.sh

createProfile $1
