#!/bin/bash
# Description
#   Lists out enabled packages in a profile.
#
# Syntax:
#   $0 profileName [--short]
#     profileName is the name for which the profile is programatically referenced.
#
# Examples:
#   Lists the profiles including any symlink infomation.
#     $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh

profileName="$1"

if [ "$short" != '' ]; then
	ls -1 "$configDir"/profiles/"$profileName"/packages
else
	resolveSymlinks "$configDir"/profiles/"$profileName"/packages | while read packageName pathToPackage;do
		repoName=`echo $pathToPackage| sed "s#^.*repos/##g;"'s#/.*$##g'`
		echo "$packageName	$repoName	$pathToPackage"
	done | tabsToSpacedDashes
fi
