#!/bin/bash
# Description
#   Removes a profile.
#   Note that this can not be undone.
#
# Syntax:
#   $0 profileName
#     profileName is the name for which the profile is programatically referenced.
#
# Examples:
#   Removes a profile called "lite"
#     $0 lite

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. "$libDir"/packages.sh

removeProfile $1
