#!/bin/bash
# Description
#   Remove a repository
#
# Syntax:
#   $0 repoName
#     repoName is the name used to refer to the repository.
#
# Examples:
#   Add a directory structure.
#     $0 /usr/local/something

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh

removeRepo "$1"
