#!/bin/bash
# Description
#   Installs a repository from start to finish. **Most users will want this.
#
# Syntax:
#   $0 repoAddress
#     repoAddress is where to get the repo from.
#
# Examples:
#   Install a github repo.
#     $0 http://github.com/ksandom/something
#
#   Another way to install the same repo.
#     $0 git@github.com:ksandom/something
#
#   How to install a repo that is stored on your local machine.
#     $0 /usr/local/something

requiredParms="$1"
checkoutDir="repoInstall-$$"
. `dirname $0`/libs/includeLibs.sh
. $libDir/getRepo.sh

if [ "`echo $2 | grep '\(@\|://\)'`" != '' ]; then
	getRepo "$checkoutDir" "$2"
else
	addPretendRepo "$checkoutDir" "$1"
fi

cd "$configDir/repos/$checkoutDir"
# TODO detect name
# TODO detect conflict
	# TODO clean up and abort
# TODO mv to final destination
# TODO create profile
# TODO enable packages
# TODO create executable
