#!/bin/bash
# Description
#   Lists out currently installed repos.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the current repos including any symlink infomation.
#     $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#     $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh
. $libDir/repoParms.sh


case $1 in
	'--short')
		ls -1 "$configDir"/repos
	;;
	*)
		resolveSymlinks "$configDir"/repos | while read in;do
			echo "$in" | tabsToSpacedDashes
			name=`echo "$in" | cut -d\	 -f1`
			repoGetParms "$name"
			echo
		done
	;;
esac
