#!/bin/bash
# Description
#   Installs a repository from start to finish. **Most users will want this.**
#
# Syntax:
#   $0 repoAddress [overRideRepoName]
#     repoAddress is where to get the repo from.
#     overRideRepoName allows you to resolve a conflict if two different repositories specify the same name. 
#       Note that you will be in for many headaches if you need to do this.
#       I recommend that you uninstall one of the two repos.
#
# Examples:
#   Install a github repo.
#     $0 http://github.com/ksandom/something
#
#   Another way to install the same repo.
#     $0 git@github.com:ksandom/something
#
#   How to install a repo that is stored on your local machine.
#     $0 /usr/local/something

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. $libDir/repoInstall.sh
. $libDir/getRepo.sh
. $libDir/repoParms.sh
. $libDir/packages.sh
. $libDir/installLibs.sh

repoAddress="$1"
overRideRepoName="$2"

installRepo "$repoAddress" "$overRideRepoName"
