#!/bin/bash
# Description
#   Lists out currently installed repos.
#
# Syntax:
#   $0 [--short]
#
# Examples:
#   Lists the current repos including any ssymlink infomation.
#   $0
#   Lists the current repos without symlink information. This is what you will want if you want to write scripts using this script.
#   $0 --short

requiredParms="none"
. `dirname $0`/libs/includeLibs.sh

# TODO Check this works as expected on other systems. It should produce output like this:
#  aws-sdk-for-php -> /home/ksandom/files/develop/externalRepos/aws-sdk-for-php/

case $1 in
	'--short')
		ls -1 "$configDir"/repos
	;;
	*)
		resolveSymlinks "$configDir"/repos | tabsToSpacedDashes
	;;
esac
