#!/bin/bash
# Description
#   List the parameters for a repository. Use this for creating executables.
#
# Syntax:
#   $0 repoName parameterName "value"
#     repoName is the name of the repository you'd like to set the parameter in.
#
#     IMPORTANT: You can not use commas (,) in any of these parameters.
#
# Examples:
#   List the parameters for the doneIt repository.
#     $0 doneIt

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh
. $libDir/repoParms.sh

repoGetParms "$1"
