#!/bin/bash
# Description
#   Remove a repository
#
# Syntax:
#   $0 repoName
#     repoName is the name we use to refer to the repository.
#
# Examples:
#   Add a directory structure.
#   $0 /usr/local/something

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh

cd "$configDir"/repos

if [ ! -e "$1" ]; then
	echo "Could not find repo \"$1\". You can list them using repoList."
	exit 1
fi

if [ -h "$1" ]; then # Symlink (pretend repo)
	rm "$1"
elif [ -d "$1" ] # Directory
	rm -Rf "$1"
fi
