#!/bin/bash
# Description
#   Adds a pretent repository (a complete directory structure that is not yet a repository). This is useful for something that is still in the experimentation stage.
#
# Syntax:
#   $0 pathToDirectoryStructure
#
# Examples:
#   Add a directory structure.
#   $0 /usr/local/something

requiredParms="$1"
. `dirname $0`/libs/includeLibs.sh

cd "$configDir"/externalLibraries
ls -l
