#!/usr/bin/php
<?php
# Copyright (c) 2012, Kevin Sandom under the BSD License. See LICENSE for full details.
 
define('programName', '~%programName%~');
$description="A commandline tool/API for doing awesome stuff on many nodes of a cluster.";
$profile=programName;

define('configDir', '~%configDir%~');
define('storageDir', '~%storageDir%~');
define('installType', '~%installType%~');
define('binExec', '~%binExec%~');

include configDir.'/core.php';

# Early processing of -q
$verbosity=0;
if (isset($argv[1]))
{
	$firstArg=$argv[1];
	if ($firstArg=='-q' or $firstArg=='--quiet') $verbosity=-1;
	elseif ($firstArg=='--debugStartup') $verbosity=4;
}


# initiate core
$core=core::assert($verbosity);
$core->set('General', 'EOL', "\n");
$core->set('General', 'configDir', configDir);
$core->set('General', 'storageDir', storageDir);
$core->set('General', 'installType', installType);
$core->set('General', 'binExec', binExec);
$core->set('General', 'profile', $profile);
$core->set('General', 'hostsDir', storageDir.'/data/1LayerHosts');
$core->set('General', 'programName', programName);
$core->set('General', 'description', $description);
include (configDir.'/interfaces/commandLine.php');
$core->setRef('CommandLine', 'arguments', $argv);
loadModules($core, configDir."/profiles/$profile/modules");
$core->callFeature("registerForEvent", "Mass,finishLate,outNow");

$core->go();

?>
